### ISSUE TITLE
Circuit board schematic 

### ISSUE THREAD

**Issue by gullwing12** [realA10001986/Dash-Gauges#1]
Is there a schematic for the gauge cluster board that can be used in diagnosis an issue?

**Comment by realA10001986** [comment]
Unfortunately no. I have skipped the schematics step and designed the board directly as a PCB. Do you have an issue at hand?

**Comment by gullwing12** [comment]
Unfortunately I do. I am getting power to esp32 but nowhere else. Installed DTMPropinstaller powered up gauge cluster nothing. Then installed firmware it did a reboot and still nothing. Now it will not connect to web and is not showing as an option for a local connection either. I have used both 12 and 5 volt connections. I was thinking g I might have a faulty esp32.

**Comment by realA10001986** [comment]
So there is no "NP-AP" WiFi network after installing DTMPropInstaller, and no "DG-AP" network after installing the gauges firmware? How did you install the gauges firmware? Compiled and uploaded through USB?

What about connecting the ESP32 dev board alone (removed from the gauges PCB) to a computer using USB? Does the LED on the devboard go on?

If you compiled yourself: Uncomment the "#define DG_DBG" line in dg_global.h and re-install, then look at the serial monitor to see if the ESP does something.

Unless you defined the gauge types, the gauges won't show anything; however, at least the backlights should come on. Do the relays click?

**Comment by gullwing12** [comment]
There was NP AP then after the firmware it update the name to gauges not DG-AP. Firmware was done via the Dr brown web site. Esp32 removed the light does come on when connected to a computer. There is a audible click when you poer the gauges. Also noted if you apply a little pressure to the esp33 the light will dim and the relay will click. Triple checked all my connection l, all seems good.

**Comment by realA10001986** [comment]
OK, so the relays appear to work - that is the click you hear. That also means that the ESP32 is working, because it causes this click by software. 

What about the gauges' backlight? Does this come on at some point? (That is what the click does. If the lights are not coming on: Did you configure the "INT"/"EXT" light power solder jumper?)

"NP-AP"/"DG-AP" is the name of the WiFi network, not the hostname. So you need to connect to WiFi-network "DG-AP", and then navigate the browser to http://192.168.4.1 or http://gauges.local - Did I understand correctly that there is no "DG-AP" network? Are you sure you did a proper re-scan of available WiFi networks? Sometimes it takes a while for the computer to pick up a new network.

You need to configure a gauge type for each of the gauges - in the Config Portal. If no gauge types are defined/configured, the gauges won't move.

**Comment by realA10001986** [comment]
Can you upload a hi-res picture of the PCB?

**Comment by gullwing12** [comment]
As soon as I can, I will. I think it is something simple, it is just my knowledge base on this sort of thing is lacking.

**Comment by gullwing12** [comment]
![20240619_175854](https://github.com/realA10001986/Dash-Gauges/assets/79131610/a18870df-b454-450f-b74e-0709ffc15831)
![20240619_175917](https://github.com/realA10001986/Dash-Gauges/assets/79131610/8e52a0d3-c672-44e1-962f-5e358eca19ed)

**Comment by realA10001986** [comment]
You should check all your soldering, that does not look good frankly. Sorry to say but it wouldn't surprise me if half of them don't make contact.

- Also, you joined the "EXT" solder jumper for the lights, why? Are you planning on using a separate power supply for the lights? If not, please join INT and open "EXT".

- The board looks damaged around the two LED solder pads, I am not sure those will work. R7 and R8 are bridged with a wire, what's is the plan? Use a 2-3V external power supply for the lights?

- Please remove the "solder bridge" between "DG+" and "+" on the 12V connector. Those should ONLY be joined if the board is powered by 12V. There is a reason for not connecting them on the PCB.

- Make sure, DIG4 is open, it looks like there is solder on the pad although you meant to close ANA4.

- It looks like you are in a car, are those 12V wires? NEVER connect 12V to the 5V connector, this will definitely blow the electronics.

**Comment by realA10001986** [comment]
I am closing this for now as that's not an issue on my side; feel free to open a discussion thread if you need further assistance.
