### ISSUE TITLE
Side swotch

### ISSUE THREAD

**Issue by gullwing12** [realA10001986/Dash-Gauges#2]
What type of switch is used for the side switch  empty/refill sequences (green 5)? Momentary or on/off?

**Comment by realA10001986** [comment]
Ah.... didn't mention that. Maintained (on/off).

**Comment by gullwing12** [comment]
Thank you

**Comment by gullwing12** [comment]
Can the sound files or logic be switched for the door opening/closing? Utilizing the door switch  the closing soind is played when door is opening and opening sound is played when door is closed.

**Comment by realA10001986** [comment]
Will check tonight if I accidently reversed the logic.

But that aside: 

Depends on your actual door switch.... does that switch open when the door closes, or close when the door closes?

The option "Switch closes when door is closed" in the Config Portal needs to be set according to the behavior of your switch.

**Comment by gullwing12** [comment]
Thank you, that worked. All is good

**Comment by realA10001986** [comment]
Out of curiosity: What types of meters are you using? Any of the ones I tested, or different ones?

**Comment by gullwing12** [comment]
I got a lot of analog gauges mainly for the actual Roentgen gauge and pieced together some gauges out of that. Basically a hog podge of meters.

**Comment by realA10001986** [comment]
Ah ok

**Comment by gullwing12** [comment]
Idea for an improvement. Would it be possible to have the door sounds work with the unit off? Maybe a separate battery power supply.
