### ISSUE TITLE
DWG Files for 142 VU Meter

### ISSUE THREAD

**Issue by TechieNetGuy** [realA10001986/Dash-Gauges#3]
Just wanted to let you know that I used the DWG for the 142 meter, and everything was produced perfect. You had mentioned to report any problems, but I figured a report of no problems would be a good idea as well.

**Comment by realA10001986** [comment]
Awesome, thank you!

If you need assistance with the meters and/or the Control Board, let me know.

**Comment by realA10001986** [comment]
Hi, does your 142 have a long or a short pointer? If it's a "long pointer" version, could you do me a favor and put the dial into a scanner and send me the scan? 600 dpi if possible. Thanks!
