### ISSUE TITLE
Gauge type not saving

### ISSUE THREAD

**Issue by doc1011** [realA10001986/Dash-Gauges#5]
Hi 

Followed the instructions for the adjustment for the CircuitSetup board. The instructions suggest setting the board type to 'Generic Analog 0-2.048V' if the gauge shoots the pointer. I tried this however after saving the settings it defaults back to 'Generic Analog 0-4.095V'. This still work with the trimpot adjusted way down and the 'Roentgens' full percentage set at 60. I'm not sure if this is expected but thought worth mentioning as it won't save the gauge type as 'Generic Analog 0-2.048V'.

Cheers

![Screenshot 2024-08-29 at 10 37 38](https://github.com/user-attachments/assets/b6de0979-5556-4b32-b7c9-2ad2af3914a6)

**Comment by realA10001986** [comment]
Yes, that's a bug. Will fix shortly.

**Comment by doc1011** [comment]
Great, thanks!

**Comment by realA10001986** [comment]
Fixed.
